import Link from "next/link";
import { ArrowLeft, ArrowRight } from "lucide-react";
import { Header, Footer } from "@/components/brand";
import { Rules } from "@/components/rules";
import { VaultDemo } from "@/components/vault-demo";

export default function RulesPage() {
  return <div className="site-shell new-game"><Header/><main className="rules-page"><Link href="/" className="text-link"><ArrowLeft size={16}/> Back to play</Link><span className="eyebrow">THE NEW NEON HEIST</span><h1>Tap a vault.<br/><span>That’s your move.</span></h1><p className="lead">You’re trying to leave with more loot than your friends.<br/>Start with the demo. Then try one round against Byte.</p><VaultDemo/><Rules/><aside className="rules-example"><span className="eyebrow">AN EXAMPLE</span><h3>$10,000. Two players. $5,000 each.</h3><p>You and a friend pick the same vault. You split the loot. If you were the only one there, you’d take all $10,000. A bigger vault can be crowded, so a smaller empty vault can be the better choice.</p></aside><details className="extra-rules"><summary>The smaller details</summary><p>Play against the computer or invite 2–8 people on separate devices. Everyone marks ready in a friends room; the host starts. You get 20, 45, or 60 seconds to choose. Locked choices cannot change. If time runs out before you choose, you skip that round.</p><p>Results stay on screen for eight seconds, then the next round starts automatically. Your runner is assigned for you; the server rests a used runner for one round and sends an available one next time. Runners do not change the payout.</p><p>Your one Double Cross is spent when you submit it, including when an alarm stops the payout. Loot is divided into whole credits; leftover credits stay in the vault. These are fictional game credits.</p><p>Reconnect using the same browser to keep your seat. Leaving a friends lobby passes hosting to the next player. Byte chooses before you and cannot change its plan after seeing yours. The computer option is extra practice; friends rooms still support multiplayer across devices.</p></details><Link href="/" className="button primary">Let’s play <ArrowRight size={18}/></Link></main><Footer/></div>;
}
